### PR TITLE
New recipe with updated dependencies and maintainer

### PR DESCRIPTION
**Pull request by thewchan**
Checking to see why pip check fails

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@hmaarrfk sorry for the ping; trying here but there's not a lot of feedback to debug why pip check is failing here...

**Comment by hmaarrfk** [comment]
does backporting https://github.com/uqfoundation/multiprocess/pull/197  help

**Comment by thewchan** [comment]
@hmaarrfk  we can try; using a patch?

**Comment by hmaarrfk** [comment]
yes, you can get the patch by going to the url and adding a `.patch` at the end

**Comment by thewchan** [comment]
> yes, you can get the patch by going to the url and adding a `.patch` at the end

@hmaarrfk I didn't know this! I did this the long way this time but will note for future reference

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@hmaarrfk I don't think I got it to work?

**Comment by hmaarrfk** [comment]
No you did not get it to work.

It helps to run things in debug mode where you can see that the `setup.cfg` file uploaded to pypi.org is wrong. 

I think that is what the patch tries to resolve.

Instead, I had to delete it:
https://github.com/conda-forge/multiprocess-feedstock/pull/54

**Comment by thewchan** [comment]
got it, I can close this one in favor of yours if that helps

**Comment by hmaarrfk** [comment]
No. I explicitly said I don't want that in mine. You should take ownership

**Comment by thewchan** [comment]
@jschueller and @synapticarbors thanks to @hmaarrfk's help go this to work with pip check; this should alleviate many downstream woes (we hope anyway). Appreciate a review and merge 🙏

**Pull request merged**
