### PR TITLE
build extension and test import

### LINKED ISSUE #6: Extension not built
```
    building '_multiprocess' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/py2.7
    creating build/temp.linux-x86_64-2.7/py2.7/Modules
    creating build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess
    gcc -pthread -fno-strict-aliasing -m64 -fPIC -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/home/conda/feedstock_root/build_artifacts/multiprocess_1538994233885/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/python2.7 -c py2.7/Modules/_multiprocess/multiprocess.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/multiprocess.o
    unable to execute 'gcc': No such file or directory


    -----------------------------------------------------------------------
    WARNING: The C extensions could not be compiled
    -----------------------------------------------------------------------

    Maybe you do not have a C compiler installed on this system?
    The reason was:
      File "<string>", line 1, in <module>

      File "/tmp/pip-req-build-pPMKSO/setup.py", line 415, in <module>
        msg = BUILD_WARNING % '\n'.join(traceback.format_stack())


    This is just a warning as most of the functionality will work even
    without the updated C extension.  It will simply fallback to the
    built-in _multiprocessing module.  Most notably you will not be able to use
    FORCE_EXECV on POSIX systems.  If this is a problem for you then please
    install a C compiler or fix the error(s) above.
    -----------------------------------------------------------------------
```

this causes trouble like this: https://github.com/uqfoundation/pathos/issues/121

### PR DESCRIPTION
**Pull request by marscher**
Fixes #6

### CODE REVIEW

**Comment by marscher** [comment]
@conda-forge-admin please rerender

**Comment by marscher** [comment]
@jschueller please review, I just added a c compiler to the recipe and re-rendered it to ensure we have the extension in place.

**Comment by jschueller** [comment]
SGTM

**Review by jschueller — APPROVED** [review]

**Comment by marscher** [comment]
Thanks a lot for the quick response!

**Pull request merged**
